### ISSUE TITLE
Merge Mars-app library with orogen integrations

### ISSUE THREAD

**Issue by goldhoorn** [rock-simulation/simulation-orogen-mars#12]
Currently a lot of code in the orogen integration is a copy of the 'old" mars_app.
The functionality of mars_app was extracted and should be merged with the orogen of mars.

See https://github.com/rock-simulation/mars/blob/master/app/src/MARS.cpp 
vs.
https://github.com/rock-simulation/simulation-orogen-mars/blob/master/tasks/Task.cpp

**Comment by malter** [comment]
Is done.
