### ISSUE TITLE
branch "depricated naming" fails to build with Rock 1408

### ISSUE THREAD

**Issue by planthaber** [rock-simulation/simulation-orogen-mars#20]
Shouldn't 1408 use the 1408 branch?

> /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/stable/node/Ubuntu_LTS/dev/simulation/orogen/mars_core/tasks/MarsRotatingLaserRangeFinder.cpp:5:40: fatal error: mars/sim/RotatingRaySensor.h: No such file or directory
     #include <mars/sim/RotatingRaySensor.h>
                                            ^
    compilation terminated.
    make[2]: *** [tasks/CMakeFiles/simulation-tasks-gnulinux.dir/MarsRotatingLaserRangeFinder.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/stable/node/Ubuntu_LTS/dev/simulation/orogen/mars_core/tasks/ForceTorque6DOF.cpp: In member function 'virtual void simulation::ForceTorque6DOF::update(double)':
    /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/stable/node/Ubuntu_LTS/dev/simulation/orogen/mars_core/tasks/ForceTorque6DOF.cpp:56:13: error: 'class mars::sim::Joint6DOFSensor' has no member named 'getForceData'
    /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/stable/node/Ubuntu_LTS/dev/simulation/orogen/mars_core/tasks/ForceTorque6DOF.cpp:57:13: error: 'class mars::sim::Joint6DOFSensor' has no member named 'getTorqueData'

**Comment by goldhoorn** [comment]
On 20.04.2015 10:11, Steffen Planthaber wrote:
>
> Shouldn't 1408 use the 1408 branch?
>
>
????

It does not?


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by planthaber** [comment]
Correct:
https://github.com/rock-simulation/package_set/blob/master/overrides.rb

**Comment by goldhoorn** [comment]
1408 was a inconsistend release furthermore release cannot be patched and 1408 is now outdated please try 1505 instead.
